"""checking from local machine

Revision ID: 51791669d3f4
Revises: 001
Create Date: 2026-08-11 20:14:21.808959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51791669d3f4'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menus_seller_id_fkey', 'menus', type_='foreignkey')
    op.create_foreign_key(None, 'menus', 'seller_profiles', ['seller_id'], ['id'])
    op.create_index(op.f('ix_ratings_rater_id'), 'ratings', ['rater_id'], unique=False)
    op.drop_constraint('seller_profiles_id_fkey', 'seller_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'seller_profiles', 'users', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller_profiles', type_='foreignkey')
    op.create_foreign_key('seller_profiles_id_fkey', 'seller_profiles', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ratings_rater_id'), table_name='ratings')
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.create_foreign_key('menus_seller_id_fkey', 'menus', 'seller_profiles', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
